name: amuse_flutter
description: Amuse_test flutter app by Kim Min Ho.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.1.0
  equatable: ^1.0.1
  http: ^0.12.0+3
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  json_annotation: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  build_runner: ^1.7.2


flutter:
  uses-material-design: true
